language: node_js
node_js:
  - 'node'

script:
  nyc yarn test

after_success:
  yarn coverage

services:
  - postgresql


before_script:
  - psql -c 'create database test;' -U postgres
  - node ./db/create-table.js pg://postgres@127.0.0.1:5432/postgres
